name: fitness_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # BloC State Management
  flutter_bloc: ^9.0.0

  # Firebase (Mises à jour pour compatibilité avec les versions récentes)
  firebase_core: ^3.11.0  # Anciennement ^3.11.0 (downgrade pour compatibilité)
  firebase_auth: ^5.4.2  # Anciennement ^5.4.2 (downgrade pour compatibilité)
  firebase_storage: ^12.4.2

  # iOS Icons
  cupertino_icons: ^1.0.2

  # Page View Dots Indicator
  dots_indicator: ^4.0.0

  # Percent Circle Indicator
  percent_indicator: ^4.2.4

  # URL Launcher
  url_launcher: ^6.0.9

  # Workout Details Sliding Panel
  sliding_up_panel: ^2.0.0+1

  # Video Player (Mise à jour pour compatibilité avec Flutter Web)
  video_player: ^2.7.0  # Anciennement ^2.1.12 (mise à jour pour compatibilité)
  chewie: ^1.7.4  # Anciennement un dépôt Git, remplacé par la version stable

  # Countdown Timer
  custom_timer: ^0.2.3

  # Image Picker (Mise à jour pour éviter conflits)
  image_picker: ^1.0.7  # Anciennement ^1.1.2 (downgrade pour compatibilité)

  # Reminder Notifications (Mise à jour pour compatibilité avec Flutter Web)
  flutter_local_notifications: ^18.0.1  # Anciennement ^18.0.1 (downgrade nécessaire)

  # Native Timezone
  flutter_native_timezone: ^2.0.0

  # Permission Handler
  permission_handler: ^11.3.1

  # Wakelock (Ajout de `wakelock_plus` à la place de `wakelock`)
  wakelock_plus: ^1.1.2  # Remplace `wakelock` pour compatibilité Web

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/images/auth/
    - assets/images/home/
    - assets/images/exercises/
    - assets/icons/home/
    - assets/icons/workouts/
    - assets/icons/social_networks/
    - assets/videos/workouts/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR/NotoSansKR-Bold.otf
          weight: 700

