// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8gUa8ngV4im8neK2GeWn8H3aL2ROHz6A',
    appId: '1:789355706227:web:4867b5aac5863f3c553706',
    messagingSenderId: '789355706227',
    projectId: 'fitness-5b83e',
    authDomain: 'fitness-5b83e.firebaseapp.com',
    storageBucket: 'fitness-5b83e.firebasestorage.app',
    measurementId: 'G-ZSHXSMQM5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWwjRlr7Vp06FEX51X8xQf1tNnz-bWl84',
    appId: '1:789355706227:android:accde6d685cd5c8c553706',
    messagingSenderId: '789355706227',
    projectId: 'fitness-5b83e',
    storageBucket: 'fitness-5b83e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV1UFviPml-B09y_mAO4WHou9CVlYKezM',
    appId: '1:789355706227:ios:f046cffba16f0ed7553706',
    messagingSenderId: '789355706227',
    projectId: 'fitness-5b83e',
    storageBucket: 'fitness-5b83e.firebasestorage.app',
    iosBundleId: 'com.chiraz.fitnessapp',
  );
}
